// Code generated by conversion-gen. DO NOT EDIT.

package rest

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// NodePoolSpecPassthrough mirrors NodePoolSpec from upstream HyperShift
type NodePoolSpecPassthrough struct {
}
