// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cdoan1/hyperfleet-api-codegen/api/v1alpha1"
	"github.com/cdoan1/hyperfleet-api-codegen/pkg/conversion"
	"github.com/cdoan1/hyperfleet-api-codegen/pkg/conversion/v1alpha1/rest"
)

// ProjectNodePool converts CRD NodePool to REST (visible fields only)
func ProjectNodePool(crd *v1alpha1.NodePool) *rest.NodePool {
	if crd == nil {
		return nil
	}

	return &rest.NodePool{
		ID:     string(crd.UID),
		Spec:   projectNodePoolSpec(crd.Spec),
		Status: projectNodePoolStatus(crd.Status),
	}
}

// projectNodePoolSpec converts CRD NodePoolSpec to REST
func projectNodePoolSpec(crd v1alpha1.NodePoolSpec) rest.NodePoolSpec {
	return rest.NodePoolSpec{
		ClusterRef: crd.ClusterRef,
		DisplayName: crd.DisplayName,
		AutoRepair: crd.AutoRepair,
		Labels: crd.Labels,
		NodePool: projectNodePoolSpecPassthrough(crd.NodePool),
	}
}

// projectNodePoolStatus converts CRD NodePoolStatus to REST
func projectNodePoolStatus(crd v1alpha1.NodePoolStatus) rest.NodePoolStatus {
	return rest.NodePoolStatus{
		State: crd.State,
		Conditions: crd.Conditions,
		Replicas: crd.Replicas,
		ReadyReplicas: crd.ReadyReplicas,
		AvailableReplicas: crd.AvailableReplicas,
	}
}

// UnprojectNodePool converts REST NodePoolSpec to CRD with service-set enrichment
func UnprojectNodePool(spec *rest.NodePoolSpec, enrichment *conversion.ServiceSetFields) *v1alpha1.NodePoolSpec {
	if spec == nil {
		return nil
	}

	crdSpec := &v1alpha1.NodePoolSpec{
		// Visible fields from REST request
		ClusterRef: spec.ClusterRef,
		DisplayName: spec.DisplayName,
		AutoRepair: spec.AutoRepair,
		Labels: spec.Labels,
		NodePool: unprojectNodePoolSpecPassthrough(spec.NodePool),
	}

	// Service-set fields from platform enrichment
	if enrichment != nil {
		crdSpec.AccountID = enrichment.AccountID
		crdSpec.InternalPoolID = enrichment.InternalPoolID
	}

	return crdSpec
}

// projectNodePoolSpecPassthrough converts CRD passthrough to REST
func projectNodePoolSpecPassthrough(crd v1alpha1.NodePoolSpecPassthrough) rest.NodePoolSpecPassthrough {
	return rest.NodePoolSpecPassthrough{
	}
}

// unprojectNodePoolSpecPassthrough converts REST passthrough to CRD
func unprojectNodePoolSpecPassthrough(rest rest.NodePoolSpecPassthrough) v1alpha1.NodePoolSpecPassthrough {
	return v1alpha1.NodePoolSpecPassthrough{
	}
}

