// Code generated by marker-scanner. DO NOT EDIT.

package registry

// WriteMode defines how a field can be mutated by customers
type WriteMode string

const (
	// Mutable fields can be set on create and changed on update
	Mutable WriteMode = "mutable"

	// Immutable fields can be set on create but cannot be changed on update
	Immutable WriteMode = "immutable"

	// ServiceSet fields are set by the platform and cannot be set by customers
	ServiceSet WriteMode = "service-set"
)

// FieldMeta contains metadata for a single field
type FieldMeta struct {
	// FieldPath is the JSON path to the field (e.g., "spec.name")
	FieldPath string

	// WriteMode controls customer mutability
	WriteMode WriteMode

	// FeatureGate is the gate required to use this field (empty if no gate required)
	FeatureGate string

	// Hidden indicates if the field is excluded from OpenAPI
	Hidden bool
}

// FieldRegistry maps field paths to their metadata
var FieldRegistry = map[string]FieldMeta{
	"accountId": {
		FieldPath: "accountId",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"creatorARN": {
		FieldPath: "creatorARN",
		WriteMode: ServiceSet,
		Hidden:    true,
	},
	"deleteProtection": {
		FieldPath: "deleteProtection",
		WriteMode: Mutable,
	},
	"etcd": {
		FieldPath:   "etcd",
		WriteMode:   Immutable,
		FeatureGate: "HyperFleetEtcdConfig",
	},
	"etcd.managementType": {
		FieldPath: "etcd.managementType",
		WriteMode: Immutable,
	},
	"hostedCluster.etcd": {
		FieldPath:   "hostedCluster.etcd",
		WriteMode:   Immutable,
		FeatureGate: "HyperFleetEtcdConfig",
	},
	"hostedCluster.etcd.managementType": {
		FieldPath: "hostedCluster.etcd.managementType",
		WriteMode: Immutable,
	},
	"hostedCluster.release": {
		FieldPath: "hostedCluster.release",
		WriteMode: Immutable,
	},
	"hostedCluster.release.image": {
		FieldPath: "hostedCluster.release.image",
		WriteMode: Immutable,
	},
	"image": {
		FieldPath: "image",
		WriteMode: Immutable,
	},
	"managementType": {
		FieldPath: "managementType",
		WriteMode: Immutable,
	},
	"name": {
		FieldPath: "name",
		WriteMode: Immutable,
	},
	"region": {
		FieldPath: "region",
		WriteMode: ServiceSet,
	},
	"release": {
		FieldPath: "release",
		WriteMode: Immutable,
	},
	"release.image": {
		FieldPath: "release.image",
		WriteMode: Immutable,
	},
}
