// Code generated by marker-scanner. DO NOT EDIT.

package registry

// WriteMode defines how a field can be mutated by customers
type WriteMode string

const (
	// Mutable fields can be set on create and changed on update
	Mutable WriteMode = "mutable"

	// Immutable fields can be set on create but cannot be changed on update
	Immutable WriteMode = "immutable"

	// ServiceSet fields are set by the platform and cannot be set by customers
	ServiceSet WriteMode = "service-set"
)

// FieldMeta contains metadata for a single field
type FieldMeta struct {
	// FieldPath is the JSON path to the field (e.g., "spec.name")
	FieldPath string

	// WriteMode controls customer mutability
	WriteMode WriteMode

	// FeatureGate is the gate required to use this field (empty if no gate required)
	FeatureGate string

	// Hidden indicates if the field is excluded from OpenAPI
	Hidden bool
}

// FieldRegistry maps field paths to their metadata
var FieldRegistry = map[string]FieldMeta{}
