// Code generated by conversion-gen. DO NOT EDIT.

package conversion

import (
	corev1 "k8s.io/api/core/v1"
	configv1 "github.com/openshift/api/config/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	hypershiftv1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
)

// ServiceSetFields contains platform-managed fields injected during UnprojectX conversions
type ServiceSetFields struct {
	// AccountID is service-set (platform-managed, hidden from API)
	AccountID string `json:"accountId"`
	// AdditionalTrustBundle is service-set (platform-managed, hidden from API)
	AdditionalTrustBundle *corev1.LocalObjectReference `json:"additionalTrustBundle"`
	// Arch is service-set (platform-managed, hidden from API)
	Arch string `json:"arch"`
	// AuditWebhook is service-set (platform-managed, hidden from API)
	AuditWebhook *corev1.LocalObjectReference `json:"auditWebhook"`
	// AutoNode is service-set (platform-managed, hidden from API)
	AutoNode *hypershiftv1beta1.AutoNode `json:"autoNode"`
	// AutoScaling is service-set (platform-managed, hidden from API)
	AutoScaling *hypershiftv1beta1.NodePoolAutoScaling `json:"autoScaling"`
	// Autoscaling is service-set (platform-managed, hidden from API)
	Autoscaling hypershiftv1beta1.ClusterAutoscaling `json:"autoscaling"`
	// Capabilities is service-set (platform-managed, hidden from API)
	Capabilities *hypershiftv1beta1.Capabilities `json:"capabilities"`
	// Channel is service-set (platform-managed, hidden from API)
	Channel string `json:"channel"`
	// ClusterID is service-set (platform-managed, hidden from API)
	ClusterID string `json:"clusterID"`
	// ClusterName is service-set (platform-managed, hidden from API)
	ClusterName string `json:"clusterName"`
	// Config is service-set (platform-managed, hidden from API)
	Config []corev1.LocalObjectReference `json:"config"`
	// Configuration is service-set (platform-managed, hidden from API)
	Configuration *hypershiftv1beta1.ClusterConfiguration `json:"configuration"`
	// ControlPlaneRelease is service-set (platform-managed, hidden from API)
	ControlPlaneRelease *hypershiftv1beta1.Release `json:"controlPlaneRelease"`
	// ControllerAvailabilityPolicy is service-set (platform-managed, hidden from API)
	ControllerAvailabilityPolicy hypershiftv1beta1.AvailabilityPolicy `json:"controllerAvailabilityPolicy"`
	// CreatorARN is service-set (platform-managed, hidden from API)
	CreatorARN string `json:"creatorARN"`
	// Dns is service-set (platform-managed, hidden from API)
	Dns hypershiftv1beta1.DNSSpec `json:"dns"`
	// Etcd is service-set (platform-managed, hidden from API)
	Etcd hypershiftv1beta1.EtcdSpec `json:"etcd"`
	// Fips is service-set (platform-managed, hidden from API)
	Fips bool `json:"fips"`
	// ImageContentSources is service-set (platform-managed, hidden from API)
	ImageContentSources []hypershiftv1beta1.ImageContentSource `json:"imageContentSources"`
	// InfraID is service-set (platform-managed, hidden from API)
	InfraID string `json:"infraID"`
	// InfrastructureAvailabilityPolicy is service-set (platform-managed, hidden from API)
	InfrastructureAvailabilityPolicy hypershiftv1beta1.AvailabilityPolicy `json:"infrastructureAvailabilityPolicy"`
	// InternalID is service-set (platform-managed, hidden from API)
	InternalID string `json:"internalId"`
	// InternalPoolID is service-set (platform-managed, hidden from API)
	InternalPoolID string `json:"internalPoolId"`
	// IssuerURL is service-set (platform-managed, hidden from API)
	IssuerURL string `json:"issuerURL"`
	// KubeAPIServerDNSName is service-set (platform-managed, hidden from API)
	KubeAPIServerDNSName string `json:"kubeAPIServerDNSName"`
	// Labels is service-set (platform-managed, hidden from API)
	Labels map[string]string `json:"labels"`
	// Management is service-set (platform-managed, hidden from API)
	Management hypershiftv1beta1.NodePoolManagement `json:"management"`
	// Networking is service-set (platform-managed, hidden from API)
	Networking hypershiftv1beta1.ClusterNetworking `json:"networking"`
	// NodeDrainTimeout is service-set (platform-managed, hidden from API)
	NodeDrainTimeout *metav1.Duration `json:"nodeDrainTimeout"`
	// NodeLabels is service-set (platform-managed, hidden from API)
	NodeLabels map[string]string `json:"nodeLabels"`
	// NodeSelector is service-set (platform-managed, hidden from API)
	NodeSelector map[string]string `json:"nodeSelector"`
	// NodeVolumeDetachTimeout is service-set (platform-managed, hidden from API)
	NodeVolumeDetachTimeout *metav1.Duration `json:"nodeVolumeDetachTimeout"`
	// OlmCatalogPlacement is service-set (platform-managed, hidden from API)
	OlmCatalogPlacement hypershiftv1beta1.OLMCatalogPlacement `json:"olmCatalogPlacement"`
	// OperatorConfiguration is service-set (platform-managed, hidden from API)
	OperatorConfiguration *hypershiftv1beta1.OperatorConfiguration `json:"operatorConfiguration"`
	// PausedUntil is service-set (platform-managed, hidden from API)
	PausedUntil *string `json:"pausedUntil"`
	// PausedUntil is service-set (platform-managed, hidden from API)
	PausedUntil *string `json:"pausedUntil"`
	// Platform is service-set (platform-managed, hidden from API)
	Platform hypershiftv1beta1.NodePoolPlatform `json:"platform"`
	// Platform is service-set (platform-managed, hidden from API)
	Platform hypershiftv1beta1.PlatformSpec `json:"platform"`
	// PullSecret is service-set (platform-managed, hidden from API)
	PullSecret corev1.LocalObjectReference `json:"pullSecret"`
	// Release is service-set (platform-managed, hidden from API)
	Release hypershiftv1beta1.Release `json:"release"`
	// Release is service-set (platform-managed, hidden from API)
	Release hypershiftv1beta1.Release `json:"release"`
	// Replicas is service-set (platform-managed, hidden from API)
	Replicas *int32 `json:"replicas"`
	// SecretEncryption is service-set (platform-managed, hidden from API)
	SecretEncryption *hypershiftv1beta1.SecretEncryptionSpec `json:"secretEncryption"`
	// ServiceAccountSigningKey is service-set (platform-managed, hidden from API)
	ServiceAccountSigningKey *corev1.LocalObjectReference `json:"serviceAccountSigningKey"`
	// Services is service-set (platform-managed, hidden from API)
	Services []hypershiftv1beta1.ServicePublishingStrategyMapping `json:"services"`
	// SshKey is service-set (platform-managed, hidden from API)
	SshKey corev1.LocalObjectReference `json:"sshKey"`
	// Taints is service-set (platform-managed, hidden from API)
	Taints []hypershiftv1beta1.Taint `json:"taints"`
	// Tolerations is service-set (platform-managed, hidden from API)
	Tolerations []corev1.Toleration `json:"tolerations"`
	// TuningConfig is service-set (platform-managed, hidden from API)
	TuningConfig []corev1.LocalObjectReference `json:"tuningConfig"`
	// UpdateService is service-set (platform-managed, hidden from API)
	UpdateService configv1.URL `json:"updateService"`
}
